package Combat;

import Player_Types.Player;

import java.util.ArrayList;
import java.util.Scanner;


 //////////////// Need to Implement EVENT interface first ////////////


public class MapInteraction { // this itself should be an event
    //during post combat; give player options;
    // 1) player can proceed to a boss fight
    // 2) player can proceed to a normal fight
    // 3) player can proceed to a shop
    // 4) player can save the game
    // 5) player can quit the game
    // 6) player can view the player info
    // 7) player can view his inventory
    String previousEvent;
    Player player;
    static Scanner kbd = new Scanner(System.in);

    public MapInteraction(Player player, String previousEvent) {
        this.player = player;
        this.previousEvent = previousEvent; // added this in case if we want to make the options to vary by prevEvent.
    }

    private ArrayList<String> GetPossibleMoves() {
        return new ArrayList<>();
    }
    public String ProceedToNextEvent() {
        String proceedToChoice = null;
        boolean validInput = false;

        while (!validInput) {
            try {
                System.out.println("#############################################################################" +
                        "##################################");
                System.out.printf("What do you wanna do now?:%n"
                        + "1. Proceed to Boss Battle"
                        + "2. Proceed to Normal Battle%n"
                        + "3. Proceed to Shop%n"
                        + "4. Open Your Current Stats%n"
                        + "5. Open Your Inventory%n"
                        + "8. Save Game%n"
                        + "9. Quit Game%n");
                proceedToChoice = kbd.nextLine();
                if (proceedToChoice.equals("1") || proceedToChoice.equals("2") || proceedToChoice.equals("3") ||
                        proceedToChoice.equals("4") || proceedToChoice.equals("5") || proceedToChoice.equals("8") ||
                        proceedToChoice.equals("9")) {
                    validInput = true;
                }
            } catch (Exception e) {
            }
        }

        switch (proceedToChoice) {

            case "1":
                return "Boss"; // this returns a BossCombat generated by new CombatFactory.createCombat(this.getPlayer(), "Boss")
            case "2":
                return "Normal"; // this returns a NormalCombat created bty new CombatFactory.createCombat(this.getPlayer(), "Normal")
            case "3" :
                return "Shop"; // this returns a Shop event
            case "4" :
                return "Player Stats"; // this returns a ViewPlayerStats event
            case "5" :
                return "Player Inventory"; // this returns OpenInventory event
            case "8" :
                return "SaveGame"; // this returns a SaveGame event
            case "9" :
                return "QuitGame"; // this returns a GuitGame event
        }
        //If player gave weird response then player is forced to play a new NormalCombat.
        System.out.println("You Encountered a Monster");
        return "Normal";
    }


}
